Build Instruction Updates
ros-industrial-attic/godel pull request #127
Opened 2017-01-17 16:48 UTC by Jmeyer1292

Updates build instructions and wstool stuff.

@woodaaron Please review.

2017-01-17 19:14 UTC, woodaaron requested changes
Motoman is not needed for Godel.
ros-industrial/industrial_core is now at kinetic-devel

2017-01-17 19:33 UTC, gavanderhoorn commented
@woodaaron wrote:
> Motoman is not needed for Godel.

All the `*_sia20d_*` packages are dependent on `motoman_sia20d_support`.

2017-01-17 20:46 UTC, woodaaron commented
@gavanderhoorn wrote:
> All the `*_sia20d_*` packages are dependent on motoman_sia20d_support fi.

Fair enough. Godel will build without motoman in the build directory, and the application notes on the readme all reference the abb_irb2400 (which I use). I assumed Motoman was a legacy piece.

2017-01-17 21:00 UTC, Jmeyer1292 commented
@gavanderhoorn @woodaaron The motoman is a legacy at the moment. We should remove it (and all the dead code still referencing it) or move it in a different PR.

2017-01-17 21:11 UTC, Jmeyer1292 commented
@woodaaron I have pointed the `industrial_core` repo in the rosinstall script to point at the main one. 

I have not touched motoman dependencies. I will do it in another thread.

2017-01-17 21:15 UTC, gavanderhoorn commented on godel.rosinstall
> +    version: kinetic-devel}
Do you have a particular need to build `industrial_core` from source? If it's been released `rosdep` should just resolve the dependency to the binaries ..

2017-01-17 21:35 UTC, Jmeyer1292 commented on godel.rosinstall
> +    version: kinetic-devel}
Sure. I just tried to update and install ros-kinetic-industrial-core and it's not there yet. I will update it when these are released.

Do you have any good resources on the differences between all of the different ros dependency tools? `rosdep` vs `rosinstall` vs `wstool`? I'm slowly starting to care about being able to on-board others easily and would like to get this sorted out.

2017-01-18 20:58 UTC, woodaaron approved these changes

2017-01-18 21:02 UTC, merged