Fix for Laser Scan Paths Shorting the Part
ros-industrial-attic/godel pull request #150
Opened 2017-02-07 17:19 UTC by Jmeyer1292

At least in simulation, this PR addresses the issue where the laser scan paths do not align well with the bounding box of the points.

2017-02-20 17:28 UTC, Jmeyer1292 commented
ping @woodaaron

2017-02-20 18:58 UTC, woodaaron requested changes
Minor changes, minor comments.

2017-02-20 18:58 UTC, woodaaron commented on godel_surface_detection/src/scan/profilimeter_scan.cpp
> +  n = (rect.w / ds) + 1;
Magic number 1. Constant or explanation?

2017-02-20 18:58 UTC, woodaaron commented on godel_surface_detection/src/scan/profilimeter_scan.cpp
>    double dx, dy; //
As long as we're cleaning stuff up, would you remove the empty comment here?

2017-02-21 21:07 UTC, Jmeyer1292 commented
I have made requested changes and rebased on the new `kinect-devel`. Pending Travis, I think its ready to go.

2017-02-21 21:08 UTC, woodaaron approved these changes

2017-02-23 14:17 UTC, AustinDeric approved these changes

2017-02-23 14:18 UTC, merged