Multi Segment Keyence Paths
ros-industrial-attic/godel pull request #174
Opened 2017-03-02 00:18 UTC by Jmeyer1292

This code makes the Keyence planner use the same path transitions as we have for blending. Builds on top of #168.

2017-03-02 18:20 UTC, AustinDeric commented
It looks like some of these code changes were also included in PR #168. Specifically, godel_process_planning/src/common_utils.cpp.

@Jmeyer1292, Would it be a too much trouble to rebase and push?

Thanks!

2017-03-02 18:41 UTC, Jmeyer1292 commented
Will do

2017-03-02 20:41 UTC, Jmeyer1292 commented
Rebased

2017-03-02 22:41 UTC, AustinDeric requested changes

2017-03-02 22:41 UTC, AustinDeric commented on godel_process_planning/src/path_transitions.cpp
> +godel_process_planning::DescartesTraj godel_process_planning::toDescartesTraj(const std::vector<geometry_msgs::PoseArray> &segments, const double traverse_height, const double process_speed, boost::f
296 columns

2017-03-02 22:41 UTC, AustinDeric commented on godel_process_planning/src/path_transitions.cpp
> +  auto add_segment = [&traj, &last_pose, process_speed, conversion_fn] (const EigenSTL::vector_Affine3d& poses, bool free_last)
127 columns.  Good code though!

2017-03-02 22:41 UTC, AustinDeric commented on godel_process_planning/src/path_transitions.cpp
> +  const static double APPROACH_STEP_SIZE = 0.02; // m
Do we want to pass the step size in to the function?

2017-03-02 22:41 UTC, AustinDeric commented on godel_process_planning/src/path_transitions.cpp
> +  std::vector<ConnectingPath> result;
godel_process_planning::ConnectingPath

2017-03-02 22:41 UTC, AustinDeric commented on godel_process_planning/src/path_transitions.cpp
> +    ConnectingPath c;
godel_process_planning::ConnectingPath

2017-03-02 22:41 UTC, AustinDeric commented on godel_process_planning/src/path_transitions.h
> +                boost::function<descartes_core::TrajectoryPtPtr(const Eigen::Affine3d&, const double)> conversion_fn);
120 cols

2017-03-02 23:19 UTC, Jmeyer1292 commented on godel_process_planning/src/path_transitions.cpp
> +  std::vector<ConnectingPath> result;
Can you elaborate on this one?

2017-03-04 03:01 UTC, Jmeyer1292 commented
Rebased

2017-03-06 14:06 UTC, AustinDeric approved these changes

2017-03-06 14:09 UTC, merged