Feature/simple gui select plan
ros-industrial-attic/godel pull request #199
Opened 2017-03-16 18:59 UTC by AustinDeric

This PR allows the user to select a specific plan to simulate then execute.  This functionality is similar to the admin gui.

2017-03-20 20:54 UTC, jrgnicho commented
I just ran the blending gui with the *surface1.pcd* file and it works fairly well.  The only caveat is that you have to pass the absolute path to the file in the *pcd_location** parameter.  I'll resume reviewing the rest of the changes here.

2017-03-20 21:46 UTC, jrgnicho requested changes

2017-03-20 21:46 UTC, jrgnicho commented on README.md
> -- The industrial calibration library builds against `libceres`, an optimization library, whose installation instructions are available [here](http://ceres-solver.org/building.html).
Is this no longer true?

2017-03-20 21:46 UTC, jrgnicho commented on godel_simple_gui/include/godel_simple_gui/blending_widget.h
> + * 6. Simulating State (Simulated robot executes motion)
There are two **6.** entries

2017-03-20 21:46 UTC, jrgnicho commented on godel_simple_gui/include/godel_simple_gui/blending_widget.h
> +  void addPlans(std::vector<std::string>& plan_names);
Is the **plan_names** argument modified by the method?  If not then it should be a const argument.

2017-03-20 21:46 UTC, jrgnicho commented on godel_simple_gui/src/states/select_plans_state.cpp
>                                              new SurfaceSelectState()));
Should this condition cause the function to exit?

2017-03-22 13:33 UTC, AustinDeric commented on README.md
> -- The industrial calibration library builds against `libceres`, an optimization library, whose installation instructions are available [here](http://ceres-solver.org/building.html).
correct, no longer needed because the [industrial calibration](https://github.com/ros-industrial/industrial_calibration) repo is no longer included.

2017-03-22 13:33 UTC, AustinDeric commented on godel_simple_gui/include/godel_simple_gui/blending_widget.h
> + * 6. Simulating State (Simulated robot executes motion)
fixed.

2017-03-22 13:37 UTC, AustinDeric commented on godel_simple_gui/include/godel_simple_gui/blending_widget.h
> +  void addPlans(std::vector<std::string>& plan_names);
fixed.

2017-03-22 13:38 UTC, AustinDeric commented on godel_simple_gui/src/states/select_plans_state.cpp
>                                              new SurfaceSelectState()));
No, it actually moves the user back to the select surfaces state and gives them a message to select a surface.

2017-03-22 14:41 UTC, jrgnicho commented on godel_simple_gui/src/blending_widget.cpp
> +void godel_simple_gui::BlendingWidget::addPlans(const std::vector<std::__cxx11::string> &plan_names)
why use the cryptic **_cxx11** type?

2017-03-22 14:47 UTC, AustinDeric commented on godel_simple_gui/src/blending_widget.cpp
> +void godel_simple_gui::BlendingWidget::addPlans(const std::vector<std::__cxx11::string> &plan_names)
Fixed.

2017-03-22 17:24 UTC, jrgnicho approved these changes

2017-03-22 17:24 UTC, merged